"""Generate an incident's telemetry once, persist it as Parquet, and query it with DuckDB.

`data/incidents/<incident_id>/` holds metrics, logs and spans as Parquet plus the change log and
alert as JSON. A manifest fingerprint decides whether cached files can be reused; the content hash
is what the determinism test compares (same seed, byte-identical telemetry).
"""

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import duckdb
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

from dejavu.config import REPO_ROOT
from dejavu.sim.generators.alerts import generate_alert
from dejavu.sim.generators.events import ChangeEvent, generate_events
from dejavu.sim.generators.logs import generate_logs
from dejavu.sim.generators.metrics import OFFSETS, generate_metrics
from dejavu.sim.generators.traces import generate_traces
from dejavu.sim.scenario import Scenario

INCIDENTS_DIR = REPO_ROOT / "data" / "incidents"
GENERATOR_VERSION = 1
DATA_FILES = ("metrics.parquet", "logs.parquet", "spans.parquet", "events.json", "alert.json")


def fingerprint(scenario: Scenario) -> str:
    """Everything that determines the generated bytes."""
    payload = {
        "v": GENERATOR_VERSION,
        "scenario": scenario.model_dump(mode="json"),
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()


def _write(table: pa.Table, path: Path) -> None:
    pq.write_table(table, path, compression="zstd", use_dictionary=True)


def write_telemetry(scenario: Scenario, out_dir: Path) -> None:
    """Generate everything for one incident into `out_dir` (overwriting)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    metrics = generate_metrics(scenario)
    keys = sorted(metrics)
    n = OFFSETS.size
    _write(
        pa.table(
            {
                "component": pa.array([k[0] for k in keys for _ in range(n)], pa.string()),
                "metric": pa.array([k[1] for k in keys for _ in range(n)], pa.string()),
                "node": pa.array([k[2] for k in keys for _ in range(n)], pa.string()),
                "minute": pa.array(np.tile(OFFSETS, len(keys)), pa.int16()),
                "baseline": pa.array(np.concatenate([metrics[k].baseline for k in keys]), pa.float64()),
                "delta": pa.array(
                    np.round(np.concatenate([metrics[k].delta for k in keys]), 4), pa.float64()
                ),
            }
        ),
        out_dir / "metrics.parquet",
    )
    logs = generate_logs(scenario)
    _write(pa.table(logs.__dict__), out_dir / "logs.parquet")
    spans = generate_traces(scenario)
    _write(pa.table(spans.__dict__), out_dir / "spans.parquet")
    events = [e.model_dump(mode="json") for e in generate_events(scenario)]
    (out_dir / "events.json").write_text(json.dumps(events, indent=1, sort_keys=True))
    (out_dir / "alert.json").write_text(json.dumps(generate_alert(scenario, metrics), indent=2))
    (out_dir / "manifest.json").write_text(json.dumps({"fingerprint": fingerprint(scenario)}))


def content_hash(directory: Path) -> str:
    """SHA-256 over every data file, in a fixed order."""
    digest = hashlib.sha256()
    for name in DATA_FILES:
        digest.update(name.encode())
        digest.update((directory / name).read_bytes())
    return digest.hexdigest()


def ensure_telemetry(scenario: Scenario, root: Path = INCIDENTS_DIR) -> Path:
    """Generate the incident's telemetry unless an identical copy is already on disk."""
    out_dir = root / scenario.incident_id
    manifest = out_dir / "manifest.json"
    if manifest.exists() and json.loads(manifest.read_text()).get("fingerprint") == fingerprint(scenario):
        return out_dir
    write_telemetry(scenario, out_dir)
    return out_dir


@dataclass(frozen=True)
class MetricSeries:
    """A full-window series: offsets (minutes) with baseline and incident layers."""

    offsets: np.ndarray
    baseline: np.ndarray
    delta: np.ndarray


class TelemetryStore:
    """Read-only access to one incident's telemetry."""

    def __init__(self, directory: Path) -> None:
        self.dir = directory
        self._db = duckdb.connect()
        for name in ("metrics", "logs", "spans"):
            path = (directory / f"{name}.parquet").as_posix()
            self._db.execute(f"CREATE VIEW {name} AS SELECT * FROM read_parquet('{path}')")
        self.events = [
            ChangeEvent.model_validate(e) for e in json.loads((directory / "events.json").read_text())
        ]
        self.alert: dict[str, Any] = json.loads((directory / "alert.json").read_text())
        catalogue = self._db.execute("SELECT DISTINCT component, metric FROM metrics").fetchall()
        self._metrics: dict[str, set[str]] = {}
        for comp, metric in catalogue:
            self._metrics.setdefault(comp, set()).add(metric)

    @classmethod
    def for_scenario(cls, scenario: Scenario, root: Path = INCIDENTS_DIR) -> "TelemetryStore":
        return cls(ensure_telemetry(scenario, root))

    def close(self) -> None:
        self._db.close()

    def metrics_of(self, component: str) -> list[str]:
        return sorted(self._metrics.get(component, ()))

    def metric(self, component: str, metric: str) -> dict[str, MetricSeries]:
        """Series for a metric, keyed by node ("" for non-node metrics)."""
        rows = self._db.execute(
            "SELECT node, minute, baseline, delta FROM metrics WHERE component = ? AND metric = ? "
            "ORDER BY node, minute",
            [component, metric],
        ).fetchnumpy()
        out: dict[str, MetricSeries] = {}
        for node in dict.fromkeys(rows["node"].tolist()):
            mask = rows["node"] == node
            out[node] = MetricSeries(rows["minute"][mask], rows["baseline"][mask], rows["delta"][mask])
        return out

    def logs(
        self,
        component: str,
        start_s: float,
        end_s: float,
        *,
        levels: list[str] | None = None,
        contains: str | None = None,
    ) -> list[tuple[float, str, str, str, bool, float]]:
        """(offset_s, level, message, line, incident, draw) rows in a time range."""
        sql = [
            "SELECT offset_s, level, message, line, incident, draw FROM logs",
            "WHERE component = ? AND offset_s >= ? AND offset_s <= ?",
        ]
        params: list[Any] = [component, start_s, end_s]
        if levels:
            sql.append(f"AND level IN ({', '.join('?' for _ in levels)})")
            params += levels
        if contains:
            sql.append("AND line ILIKE ?")
            params.append(f"%{contains}%")
        sql.append("ORDER BY offset_s")
        return self._db.execute(" ".join(sql), params).fetchall()

    def traces_touching(
        self, component: str, start_ms: float, end_ms: float, operation: str | None = None
    ) -> list[dict[str, Any]]:
        """All spans of traces whose root started in the window and that include `component`."""
        match = "component = ?" + (" AND operation = ?" if operation else "")
        params: list[Any] = [component] + ([operation] if operation else [])
        rows = self._db.execute(
            f"""
            WITH roots AS (
                SELECT trace_id FROM spans
                WHERE parent_id = '' AND start_offset_ms >= ? AND start_offset_ms <= ?
            ), hits AS (
                SELECT DISTINCT trace_id FROM spans WHERE trace_id IN (SELECT trace_id FROM roots) AND {match}
            )
            SELECT * FROM spans WHERE trace_id IN (SELECT trace_id FROM hits) ORDER BY trace_id, start_offset_ms
            """,
            [start_ms, end_ms, *params],
        ).fetch_arrow_table()
        return rows.to_pylist()
